

const functions = require('firebase-functions');
const firebase = require('firebase');
const app = require('express')();
const React = require('react');
const ReactDOMServer = require('react-dom/server');
const template = require('./template');
const database = require('./firebase-database');

global.navigator = { userAgent: 'all' };
// React App
const ServerApp = React.createFactory(require('./build/server.bundle.js').default);

// Server-side Data Loading
const appConfig = functions.config().firebase;
database.initializeApp(appConfig);

// Helper function to get the markup from React, inject the initial state, and
// send the server-side markup to the client
const renderApplication = (url, res, initialState) => {
  const html = ReactDOMServer.renderToString(ServerApp({url: url, context: {}, initialState, appConfig}));
  const templatedHtml = template({body: html, initialState: JSON.stringify(initialState)});
  res.send(templatedHtml);
};


app.get('/favicon.ico', function(req, res) {
  res.sendStatus(204);
});

app.get('/', (req, res) => {
  res.set('Cache-Control', 'public, max-age=60, s-maxage=180');
    // index page. load data for all employees
    database.getAllEmployees().once('value').then(snap => {
      var employees = snap.val();
      renderApplication(req.url, res, employees);
    });
});

exports.app = functions.https.onRequest(app);


exports.fromGgn = functions.https.onRequest((req, res) => {
  res.status(200).send(`
  <!DOCTYLE html>
  <html dir="rtl" lang="he">
  <head>
    <title>Login</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://k-m-system.firebaseapp.com/assets/styles.css">
  </head>
    <body>
      <div id="root"></div>
    <!-- Client bundle generated by webpack -->
    <script src='https://k-m-system.firebaseapp.com/assets/client.form.bundle.js'></script>
    </body>
  </html>`);
});
