

// Template file that the server will use to inject the React markup and
// initial state before sending it to the client

const template = opts => {
  return `
  <!DOCTYLE html>
  <html dir="rtl" lang="he">
    <head>
    <title>Login</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="/assets/styles.css">
    <link rel="stylesheet" href="https://unpkg.com/react-table@latest/react-table.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
    <body>
      <div id="root">${opts.body}</div>
    </body>
    <script src="/__/firebase/4.8.1/firebase-app.js"></script>
    <script src="/__/firebase/4.8.1/firebase-database.js"></script>
    <script src="/__/firebase/init.js"></script>
    <script>
      window.__initialState = ${opts.initialState}
    </script>
    <!-- Client bundle generated by webpack -->
    <script src='/assets/client.bundle.js'></script>
  </html>
  `;
};

module.exports = template;
